#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = 'unknown'
__repo_version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '5e5c54a8372d85f92b8a8c88d6407681a845dea5 *'
__dependency_versions__ = {
    'boost': '1.59.lsst5',
    'python': 'unknown',
    'boost_regex': '1.59.lsst5',
    'base': '2015_10.0-1-g1d153f6+10',
    'pex_exceptions': '2015_10.0-1-gf7aee88+10',
    'numpy': '0.0.1+5',
    'utils': '2015_10.0-3-g530cd83+8',
    'daf_base': '2015_10.0-3-g4d32b56+8',
    'boost_system': '1.59.lsst5',
    'boost_filesystem': '1.59.lsst5',
    'pex_logging': '2015_10.0-1-gf6c85b3+10',
    'pex_policy': '2015_10.0-1-gd4eb80a+11',
    'mysqlclient': '5.1.73.lsst3',
    'boost_serialization': '1.59.lsst5',
    'daf_persistence': '2015_10.0-6-g5a5f333+4',
    'pex_config': '2015_10.0-1-gc006da1+10',
    'eigen': '3.2.5',
    'fftw': '3.3.4.lsst2',
    'ndarray': '10.1+54',
    'minuit2': '5.28.00.lsst2',
    'gsl': '1.16.lsst3',
    'cfitsio': '3360.lsst4',
    'wcslib': '4.14.lsst2',
    'cuda_toolkit': None,
    'afw': '2015_10.0-13-g95465d1+1',
    'boost_math': '1.59.lsst5',
    'meas_base': '2015_10.0-4-g87d2c31+10',
    'pipe_base': '2015_10.0-4-g4484ecd+2',
    'meas_algorithms': '2015_10.0-4-g270941b+2',
    'boost_test': '1.59.lsst5',
    'swig': 'unknown',
    'sdqa': None,
}
__all__ = ('__version__', '__repo_version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
